name: Publish VSCode extension
trigger: []
#   - main
#   # For patch releases
#   - release/*

pr: none

variables:
  - template: templates/variables/globals.yml

jobs:
  - job: publish_vscode
    displayName: Publish VSCode extension
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - template: ./templates/install.yml
        parameters:
          nodeVersion: "20.x"

      - script: pnpm --filter "typespec-vscode..." run build
        displayName: Build

      - script: npm run deploy
        displayName: Publish
        workingDirectory: packages/typespec-vscode
        env:
          VSCE_PAT: $(azuresdk-devdiv-openapi-extension-marketplace-devops-pat)
